## library() calls go here
library(conflicted)
library(tidyverse)
library(bomrang)
library(lubridate)
library(dotenv)
library(drake)
library(sf)
library(data.table)
library(rnaturalearth)
conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
conflict_prefer("pluck", "purrr")
conflict_prefer("map", "purrr")
library(rmarkdown)
